### OneHotEncoder
- There are generally two types:-
    1. Feature Encoding
    2. Text Encoding


In [1]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [7]:
colors = ["Red", "Green", "Blue"]
encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")

colors_2d = np.array(colors).reshape(-1, 1)
encoded = encoder.fit_transform(colors_2d)
print(encoded)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [12]:
sample = np.array(['Red', 'Green', 'Blue', 'Blue', 'Red', 'Green', 'Green', 'Red'])

encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
sample_2d = np.array(sample).reshape(-1, 1)

print(encoder.fit_transform(sample_2d))

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
# importing libraries 
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import OneHotEncoder 

# Retrieving data 
data = pd.read_csv('../DataSets/employee.csv') 

# Converting type of columns to category 
data['Gender'] = data['Gender'].astype('category') 
data['Remarks'] = data['Remarks'].astype('category') 


# Assigning numerical values and storing it in another columns 
data['Gender_'] = data[['Gender']]
data['Remarks_'] = data[['Remarks']]


# Create an instance of One-hot-encoder 
encoder = OneHotEncoder() 

# Passing encoded columns 

new_data = pd.DataFrame(encoder.fit_transform( 
	data[['Gender_', 'Remarks_']]).toarray()) 

# Merge with main 
New_df = data.join(new_data) 

print(New_df) 


    Employee_Id  Gender Remarks Gender_ Remarks_    0    1    2    3    4
0             1  Female    Nice  Female     Nice  1.0  0.0  0.0  0.0  1.0
1             2    Male   Great    Male    Great  0.0  1.0  0.0  1.0  0.0
2             3    Male   Great    Male    Great  0.0  1.0  0.0  1.0  0.0
3             4    Male    Good    Male     Good  0.0  1.0  1.0  0.0  0.0
4             5  Female    Good  Female     Good  1.0  0.0  1.0  0.0  0.0
5             6    Male   Great    Male    Great  0.0  1.0  0.0  1.0  0.0
6             7  Female    Nice  Female     Nice  1.0  0.0  0.0  0.0  1.0
7             8  Female    Good  Female     Good  1.0  0.0  1.0  0.0  0.0
8             9  Female   Great  Female    Great  1.0  0.0  0.0  1.0  0.0
9            10    Male    Good    Male     Good  0.0  1.0  1.0  0.0  0.0
10           11  Female   Great  Female    Great  1.0  0.0  0.0  1.0  0.0
11           12    Male    Good    Male     Good  0.0  1.0  1.0  0.0  0.0
12           13    Male   Great    Mal